feat: first implement
eggjs/egg-view-ejs pull request #1
Opened 2017-02-16 10:10 UTC by popomore

2017-02-16 10:15 UTC, atian25 commented
前几天有人好像也做了个，不知道有没有占了 npm 包名

2017-02-16 10:18 UTC, popomore commented
@cycgit

2017-02-16 10:42 UTC, popomore commented
改成 ejs2 好了

2017-02-16 10:44 UTC, atian25 commented
找他要下好了，明天问问。合并成一个库

2017-02-16 12:32 UTC, atian25 requested changes
这个库没有 shtml 还有 injectCsrf 么？

2017-02-16 12:32 UTC, atian25 commented on README.md
> +  package: 'egg-egg-view-ejs',
duplicate

2017-02-16 12:32 UTC, atian25 commented on config/config.default.js
> +  root: 'app/view',
统一为 dir

2017-02-16 12:32 UTC, atian25 commented on lib/view.js
> +    this.viewConfig = ctx.app.config.ejs;
this.config

2017-02-16 12:32 UTC, atian25 commented on package.json
> +    "egg-plugin",
多一个 egg-view

2017-02-16 12:32 UTC, atian25 commented on package.json
> +    "egg": "^0.7.0",
autod

2017-02-16 12:52 UTC, popomore commented
ejs 太简单了，连 layout 都没有，有些功能等真正有需求再看吧

2017-02-16 12:55 UTC, atian25 reviewed
其他+1

2017-02-16 12:55 UTC, atian25 commented on lib/view.js
> +  get helper() {
默认就是这个吧？干掉？

2017-02-16 12:59 UTC, popomore commented
默认是空的吧

2017-02-16 13:00 UTC, popomore commented on config/config.default.js
> +  root: 'app/view',
这个 root 也是 ejs 的参数

2017-02-16 15:05 UTC, atian25 commented on config/config.default.js
> +  root: 'app/view',
对外统一暴露 dir，内部转为 root 给 ejs 吧

2017-02-16 15:05 UTC, atian25 commented on config/config.default.js
> +  root: 'app/view',
不过之前的 dir 是绝对路径

2017-02-16 15:27 UTC, popomore commented
修了一个 root 的 bug，可以引绝对路径了

2017-02-16 15:32 UTC, popomore commented on config/config.default.js
> +  root: 'app/view',
感觉不需要加这个约定吧，各个模板差异很大，我之前是想加一个模板 loader 功能，不过抽象程度还没想好。

2017-02-16 15:38 UTC, atian25 commented on config/config.default.js
> +      root: path.join(appInfo.baseDir, 'app/view'),
这个还改 dir 么？如果不改就要改下 view 规范那边的描述

2017-02-16 15:38 UTC, atian25 commented on config/config.default.js
> +    ejs: {
配置项应该是 view 吧？

2017-02-16 15:41 UTC, popomore commented on config/config.default.js
> +      root: path.join(appInfo.baseDir, 'app/view'),
恩，可以改成 root

2017-02-16 15:41 UTC, popomore commented on config/config.default.js
> +      root: path.join(appInfo.baseDir, 'app/view'),
我们内部记得叫 loadpath

2017-02-16 15:43 UTC, atian25 commented on config/config.default.js
> +  root: 'app/view',
模板目录应该都是有的，只是引擎的 key 不一样，之前是想约定一个值，插件内部转换，这样对应用开发者是一致的。

两个都行，如果不加约定，那我明天改下文档。

2017-02-16 15:44 UTC, popomore commented on config/config.default.js
> +    ejs: {
这个改了

2017-02-16 15:44 UTC, popomore commented
再看看

2017-02-16 15:46 UTC, atian25 commented on config/config.default.js
> +      root: path.join(appInfo.baseDir, 'app/view'),
开源的时候讨论过，跟 static 插件看齐，改为 dir 了。

改规范指的是，把 dir 这个命名改为建议，而不是强制。

> 上述几条规范，是框架对 View 插件的强约束。 下文的约定，为最佳实践，非强制约束，插件开发者可以根据具体的模板引擎场景自行实现。

2017-02-17 02:07 UTC, popomore commented
@atian25 再看看

2017-02-17 02:25 UTC, atian25 approved these changes
先合吧, 然后周末的 RFC 后再改

2017-02-17 03:08 UTC, merged

2017-02-17 03:18 UTC, atian25 commented
```
➜ npm owner ls egg-view-ejs
atian25 <atian25@qq.com>
cycok <342930982@qq.com>
fengmk2 <fengmk2@gmail.com>
popomore <sakura9515@gmail.com>
```

2017-02-17 03:19 UTC, popomore commented
等 https://github.com/eggjs/egg/issues/398 改完再发 1.0 吧