fea
eggjs/egg-view-ejs pull request #2
Opened 2017-02-17 17:30 UTC by popomore

Ref https://github.com/eggjs/egg/issues/398

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2017-02-18 00:22 UTC, atian25 requested changes

2017-02-18 00:22 UTC, atian25 commented on config/config.default.js
>        debug: false,
cache 是在 view 那边配置？然后插件里面转换过来吧？

2017-02-18 00:22 UTC, atian25 commented on lib/view.js
> +    const config = Object.assign({}, this.config, options, { filename });
config -> viewOption(s)

2017-02-18 00:22 UTC, atian25 commented on lib/view.js
> +    const config = Object.assign({}, this.config, options, { filename });
或者函数入参叫 viewoption，里面的叫 option

2017-02-18 00:22 UTC, atian25 commented on lib/view.js
> -  get helper() {
没有 view helper 了？

2017-02-18 00:22 UTC, atian25 commented on test/fixtures/apps/ejs-view/app/controller/view.js
> +  }, { viewEngine: 'ejs' });
支持设置默认的 engine？

2017-02-18 07:45 UTC, popomore commented on config/config.default.js
>        debug: false,
这个 cache 是模板渲染的缓存，就是缓存 compile 后的结果，有些模板引擎如果比较粗糙的话可能没有实现这个过程。

2017-02-18 07:46 UTC, popomore commented on lib/view.js
> -  get helper() {
恩，自己覆盖 locals 里面的 helper，等之后我实现 nunjucks 的时候可以看到

2017-02-18 08:32 UTC, atian25 commented on config/config.default.js
>        debug: false,
两个 cache 担心容易被误解，回头两个插件一起看看

2017-02-18 11:12 UTC, popomore commented
一般都不用配吧
TZ | 天猪 <notifications@github.com>于2017年2月18日 周六16:32写道：

> *@atian25* commented on this pull request.
> ------------------------------
>
> In config/config.default.js
> <https://github.com/eggjs/egg-view-ejs/pull/2#discussion_r101888392>:
>
> >       * @property {String} [root=${baseDir}/app/view] - the root directory of ejs files
>       * @property {Boolean} [cache=true] - compiled functions are cached, only work using `ctx.render`
>       * @property {Boolean} [debug=false] - output generated function body
>       * @property {Boolean} [compileDebug=true] - when false no debug instrumentation is compiled
>       * @property {String} [delimiter] - character to use with angle brackets for open/close
>       * @property {Boolean} [strict=false] - when set to true, generated function is in strict mode
>       */
> -    view: {
> +    ejs: {
>        root: path.join(appInfo.baseDir, 'app/view'),
>        cache: true,
>        debug: false,
>
> 两个 cache 担心容易被误解，回头两个插件一起看看
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eggjs/egg-view-ejs/pull/2#discussion_r101888392>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAWA1XE9gpCFv7MGGG74NFr7Ftm40kRwks5rdqywgaJpZM4MEigl>
> .
>

2017-02-20 13:50 UTC, atian25 approved these changes

2017-02-21 04:21 UTC, popomore commented
基于 egg-view 改了

2017-02-21 18:18 UTC, fengmk2 approved these changes

2017-02-22 03:15 UTC, popomore commented
那这个合了发个版本

2017-02-22 03:28 UTC, atian25 approved these changes
+1 合吧

2017-02-22 03:28 UTC, atian25 commented on lib/view.js
> +    const config = Object.assign({}, this.config, viewOptions, { cache: null });
ejs 的 renderString 会 cache? 用啥 key cache 的?

2017-02-22 03:37 UTC, popomore commented on lib/view.js
> +    const config = Object.assign({}, this.config, viewOptions, { cache: null });
是按 filename  cache 的，所以 renderString 无法 cache

2017-02-22 03:48 UTC, atian25 commented on lib/view.js
> +    const config = Object.assign({}, this.config, viewOptions, { cache: null });
需要特意传递 cache: null ?  ejs.render 里面没处理?

2017-02-22 03:54 UTC, popomore commented on lib/view.js
> +    const config = Object.assign({}, this.config, viewOptions, { cache: null });
他特意处理的，传了 cache 就会报错

2017-02-22 04:05 UTC, atian25 commented on lib/view.js
> +    const config = Object.assign({}, this.config, viewOptions, { cache: null });
。。。各吧

2017-02-22 04:47 UTC, popomore commented
合了，发 1.0

2017-02-22 04:47 UTC, merged

2017-02-22 04:49 UTC, popomore commented
+ egg-view-ejs@1.0.0