add layout
eggjs/egg-view-ejs pull request #6
Opened 2017-03-24 12:52 UTC by JacksonTian

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2017-03-24 12:54 UTC, JacksonTian commented
得去改egg-mock啊～～～

2017-03-24 14:46 UTC, popomore requested changes
加个用例吧

2017-03-24 14:46 UTC, popomore commented on lib/view.js
> +    if (config.layout) {
反着判断吧，尽量都写成一行

```
if (!config.layout) return html;

```

2017-03-24 14:46 UTC, popomore commented on lib/view.js
> +  _render(filename, locals, config) {
用 symbol

2017-03-24 14:46 UTC, popomore commented
> 得去改egg-mock啊

这个啥意思

2017-03-27 08:02 UTC, popomore approved these changes

2017-03-27 12:28 UTC, merged

2017-03-27 12:31 UTC, popomore commented
+ egg-view-ejs@1.1.0